
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oodhnpyipugnxgxzbvey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZGhucHlpcHVnbnhneHpidmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Njc0MjEsImV4cCI6MjA1ODU0MzQyMX0.9pCK1iL4pvESWbxgyuD2W8QumDpIQVJVG7NzJEf4Y10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
